# Generated by Django 5.2.15 on 2026-07-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, help_text="Optional label, e.g. 'Course Fees', 'Handouts'", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts are hidden from students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bank_name', 'account_name'],
            },
        ),
    ]
