# Generated by Django 5.2.15 on 2026-08-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, default='System Administrator', help_text='Official staff role/designation displayed on Staff ID card and verification portal.', max_length=150, null=True),
        ),
    ]
