# Generated by Django 5.2.15 on 2026-07-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_industrial_training',
            field=models.BooleanField(default=False),
        ),
    ]
