# Generated by Django 5.2.15 on 2026-08-02 08:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
            ],
            options={
                'verbose_name': 'Staff / Administrator',
                'verbose_name_plural': 'Staff & Administrators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, choices=[('CEO & Founder', 'CEO & Founder'), ('Chief Executive Officer (CEO)', 'Chief Executive Officer (CEO)'), ('Managing Director', 'Managing Director'), ('Academic Director', 'Academic Director'), ('School Registrar', 'School Registrar'), ('Senior Lecturer & Instructor', 'Senior Lecturer & Instructor'), ('Academic Staff / Facilitator', 'Academic Staff / Facilitator'), ('IT Director & Systems Manager', 'IT Director & Systems Manager'), ('Bursar / Lead Accountant', 'Bursar / Lead Accountant'), ('Administrative Officer', 'Administrative Officer'), ('System Administrator', 'System Administrator')], default=None, help_text='Official staff role/designation displayed on Staff ID card and verification portal.', max_length=150, null=True),
        ),
    ]
