# Generated by Django 5.2.15 on 2026-08-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffuser_studentuser_alter_user_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='admission_year',
            field=models.PositiveIntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)]),
        ),
    ]
