# Generated by Django 5.2.15 on 2026-07-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_industrial_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Automatically generated unique Student ID format.', max_length=150, unique=True),
        ),
    ]
