# Generated by Django 5.2.15 on 2026-08-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_studentcourse_admission_year'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('email', 'role'), name='unique_email_role_not_deleted'),
        ),
    ]
