# Generated by Django 5.2.15 on 2026-08-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_unit',
            field=models.CharField(choices=[('MONTHS', 'Months'), ('WEEKS', 'Weeks')], default='MONTHS', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_value',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='enrollment_date',
            field=models.DateField(blank=True, help_text='Optional Date Joined for course duration tracking.', null=True),
        ),
    ]
