# Generated by Django 5.2.15 on 2026-08-20 21:20

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_courses(apps, schema_editor):
    StudentGroup = apps.get_model('accounts', 'StudentGroup')
    for group in StudentGroup.objects.all():
        if group.course_id:
            group.courses.add(group.course_id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_course_duration_unit_course_duration_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_groups_single', to='accounts.course'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='student_groups', to='accounts.course'),
        ),
        migrations.RunPython(migrate_existing_courses, reverse_code=migrations.RunPython.noop),
    ]
