# Generated by Django 5.2.15 on 2026-07-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_0011_user_profile_picture_url_0015_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for profile picture. Max 2MB.', null=True),
        ),
    ]
