# Generated by Django 5.2.15 on 2026-07-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_missing_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
    ]
