# Generated by Django 5.2.15 on 2026-07-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_unique_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='default_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
