# Generated by Django 5.2.15 on 2026-07-14 21:06

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_studentlearningcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, help_text='Assignment instruction files. Max 10MB. Supported: PDF, Word, Excel, PowerPoint.', null=True, upload_to='assignments/', validators=[config.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(help_text='Student submission files. Max 10MB. Supported: PDF, Word, Excel, ZIP.', upload_to='submissions/', validators=[config.validators.validate_assignment_submission_file]),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='file',
            field=models.FileField(blank=True, help_text='For videos, consider using video_url instead of uploading. Max 50MB.', null=True, upload_to='learning_content/', validators=[config.validators.validate_video_file]),
        ),
    ]
