# Generated by Django 5.2.15 on 2026-08-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_quiz_quizattempt_quizquestion_questionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner Level'), ('INTERMEDIATE', 'Intermediate Level'), ('ADVANCED', 'Advanced Level'), ('GENERAL', 'General Practice')], default='BEGINNER', max_length=20),
        ),
    ]
