# Generated by Django 5.2.15 on 2026-07-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_assignment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.URLField(blank=True, help_text='Cloudinary URL for assignment file.', null=True),
        ),
        migrations.AlterField(
            model_name='handout',
            name='file',
            field=models.URLField(help_text='Cloudinary URL for handout file.'),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='file',
            field=models.URLField(blank=True, help_text='Cloudinary URL for uploaded file (document or video).', null=True),
        ),
    ]
