# Generated by Django 5.2.15 on 2026-08-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_quiz_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='display_questions_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of questions to randomly select. Leave blank to display all.', null=True),
        ),
    ]
