# Generated by Django 5.2.15 on 2026-07-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_urlfield_for_file_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.URLField(help_text='Cloudinary URL for student submission file.'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.URLField(blank=True, help_text='Cloudinary URL for certificate file.', null=True),
        ),
    ]
