# Generated by Django 5.2.15 on 2026-08-11 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_student_group'),
        ('learning', '0006_alter_certificate_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Courses that can access this quiz.', related_name='quizzes', to='accounts.course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_quizzes', to='accounts.course'),
        ),
    ]
