# Generated by Django 5.2.15 on 2026-08-12 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_student_group'),
        ('learning', '0007_quiz_courses_alter_quiz_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.URLField(help_text='Cloudinary URL for uploaded class file or code archive.')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_groups', models.ManyToManyField(blank=True, related_name='class_materials', to='accounts.studentgroup')),
                ('assigned_students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='class_materials', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_class_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
