# Generated by Django 5.2.15 on 2026-08-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_classmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmaterial',
            name='files',
            field=models.JSONField(blank=True, default=list, help_text="List of file objects: [{'url': '...', 'name': '...', 'size': '...'}]"),
        ),
        migrations.AlterField(
            model_name='classmaterial',
            name='file',
            field=models.URLField(blank=True, help_text='Cloudinary URL for uploaded class file or code archive.', null=True),
        ),
    ]
