# Generated by Django 5.2.15 on 2026-08-20 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_studentgroup_course_studentgroup_courses'),
        ('learning', '0009_classmaterial_files_alter_classmaterial_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('days_of_week', models.JSONField(default=list, help_text="List of days of week, e.g. ['MONDAY', 'WEDNESDAY', 'FRIDAY']")),
                ('day_times', models.JSONField(blank=True, default=list, help_text="List of per-day timings: [{'day': 'MONDAY', 'start_time': '10:30:00', 'end_time': '12:00:00', 'duration_minutes': 90}, ...]")),
                ('start_time', models.TimeField(help_text='Start time of the lecture (e.g. 10:30)')),
                ('end_time', models.TimeField(help_text='End time of the lecture (e.g. 12:00)')),
                ('duration_minutes', models.PositiveIntegerField(default=90, help_text='Class duration in minutes (e.g. 45, 60, 90, 120)')),
                ('mode', models.CharField(choices=[('ONLINE', 'Online (Virtual)'), ('PHYSICAL', 'Physical (Classroom)'), ('HYBRID', 'Hybrid')], default='PHYSICAL', max_length=20)),
                ('venue_or_link', models.CharField(blank=True, help_text='Meeting URL (Google Meet / Zoom) or physical classroom room/hall.', max_length=500)),
                ('instructor_name', models.CharField(blank=True, help_text='Name of the instructor / tutor taking this lecture.', max_length=255)),
                ('color_tag', models.CharField(default='#2563eb', help_text='Hex color code or theme for timetable card display.', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Preparation notes, tools, or syllabus reference for students.')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this lecture schedule.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_groups', models.ManyToManyField(blank=True, related_name='lecture_schedules', to='accounts.studentgroup')),
                ('assigned_students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='lecture_schedules', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_schedules', to='accounts.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lecture_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time', 'created_at'],
            },
        ),
    ]
