# Generated by Django 5.2.15 on 2026-08-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminalert',
            name='alert_type',
            field=models.CharField(choices=[('ATTENDANCE_REQUEST', 'Attendance Request'), ('ASSIGNMENT_SUBMISSION', 'Assignment Submission'), ('HANDOUT_REQUEST', 'Handout Request'), ('STUDENT_ACTION', 'Student Action')], max_length=50),
        ),
    ]
